### ISSUE TITLE
Cannot negotiate a secure key exchange with OpenSSH 6.9 (Fixed in PuTTY 0.65)

### ISSUE THREAD

**Issue by Morgyn** [noodle1983/putty-nd3.x#4]
Same as detailed here for winscp http://winscp.net/forum/viewtopic.php?t=15626

**Comment by Morgyn** [comment]
http://tartarus.org/~simon-git/gitweb/?p=putty.git;a=commitdiff;h=318076a1838c0e270afc5ac5a8081b3a1273cfb4
I believe is where SSH2_MSG_KEX_DH_GEX_REQUEST is implemented

**Comment by noodle1983** [comment]
I don't have the env to verify it. 
But you can fix it since the code is there.
